//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Haat_Bazar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courrier
    {
        public int CourrierId { get; set; }
        public string CourrierName { get; set; }
        public string CourrierPhone { get; set; }
        public string CourrierAddress { get; set; }
    }
}
